### ISSUE TITLE
 How to speed up the infer process?

### ISSUE THREAD

**Issue by luoshiyong** [WuJunde/MedSegDiff#14]
for one image, model need to infer 1000(timestep), one step is about 2min, how to speed up the infer process?

**Comment by WuJunde** [comment]
Did you run it on GPU? one step is about seconds for me. btw, you can set --dpm-solver as true to speed up the convergence.

**Comment by luoshiyong** [comment]
yes, my gpu is 3080 with 12GB. In the infer process, the gpu use is 7901/12288MiB, so i think the problem is not on the gpu.

**Comment by luoshiyong** [comment]
recorrect it that one image(1000timestep) infer need 2min, not one timestep

**Comment by WuJunde** [comment]
Yes, that's a major weakness of DPM. Many works have proposed to speed up the sampling, for example, DPM-solver we deployed in the recent versions. You can set --dpm_solver True to speed up the sampling. In this case, you can set --diffusion_step 50 instead of 1000 to see a convergence, but it has a slight performance compromise.
