### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by zhao9chen99999** [WuJunde/MedSegDiff#36]
i download the  brats dataset and rename the folder as readme told,

**Comment by zhao9chen99999** [comment]
/bratsloader.py", line 107, in __init__ seqtype = f.split('_')[3].split('.')[0],IndexError: list index out of range

**Comment by 2445561011** [comment]
改成seqtype = f.split[3].split（'.'）[0]   就行了  这块代码就是取键值的

**Comment by zhao9chen99999** [comment]
I have already received your e-mail，Thanks a lot！我已收到您发送的邮件，感谢您的来信！

**Comment by zhao9chen99999** [comment]
谢谢您的回复！

现在换成了这样

依然还是报错。。

我下载的brats2020的train是369个文件夹，然后他的文件名格式和readme里面的文件名格式不一样，我自己把文件名改成了

这是我现在的文件夹结构

不知道问题出在哪。。。

 

 

发件人: ***@***.***> 代表 2445561011 ***@***.***>
答复: WuJunde/MedSegDiff ***@***.***>
日期: 2023年2月21日 星期二 20:03
收件人: WuJunde/MedSegDiff ***@***.***>
抄送: zhaochen ***@***.***>, Author ***@***.***>
主题: Re: [WuJunde/MedSegDiff] IndexError: list index out of range (Issue #36)

 

改成seqtype = f.split[3].split（'.'）[0] 就行了 这块代码就是取键值的

**Comment by zhao9chen99999** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/57703720/220532021-1292db62-8d86-4bc5-99f1-71f52b2166b8.png">

**Comment by 2445561011** [comment]
你数据的格式是按他要求的吗？   这块就是取key值的  你可以根据你的数据命名方式，将{flair、seg、t1、t1ce、t2}这些从文件名字符串中分割出来就好了。

**Comment by zhao9chen99999** [comment]
> 你数据的格式是按他要求的吗？ 这块就是取key值的 你可以根据你的数据命名方式，将{flair、seg、t1、t1ce、t2}这些从文件名字符串中分割出来就好了。

<img width="219" alt="image" src="https://user-images.githubusercontent.com/57703720/220547022-235a971a-41aa-4d96-99b8-608537a8a221.png">
这是我现在的文件格式，但是还是不行，不知道是什么问题

**Comment by 2445561011** [comment]
f.split(".")[0]     改成这个

**Comment by zhao9chen99999** [comment]
> f.split(".")[0] 改成这个

修改之后又出现了新的报错：
<img width="549" alt="image" src="https://user-images.githubusercontent.com/57703720/220821656-fb50d2f3-6fd0-4ea5-9c00-5dc46bc82147.png">

**Comment by zhao9chen99999** [comment]
w

> f.split(".")[0] 改成这个

我尝试着去修改
<img width="461" alt="image" src="https://user-images.githubusercontent.com/57703720/220822082-703e8c84-40e1-4fe5-8482-cad2545df2c4.png">
但还是出现之前的报错。。。

**Comment by zhao9chen99999** [comment]
好像是seg键值识别不出来

**Comment by jaceqin** [comment]
> > 你数据的格式是按他要求的吗？ 这块就是取key值的 你可以根据你的数据命名方式，将{flair、seg、t1、t1ce、t2}这些从文件名字符串中分割出来就好了。
> 
> <img alt="image" width="219" src="https://user-images.githubusercontent.com/57703720/220547022-235a971a-41aa-4d96-99b8-608537a8a221.png">
> 
> 这是我现在的文件格式，但是还是不行，不知道是什么问题

请问一下，可以分享一下你的数据集嘛？

**Comment by zhao9chen99999** [comment]
> > > 你数据的格式是按他要求的吗？ 这块就是取key值的 你可以根据你的数据命名方式，将{flair、seg、t1、t1ce、t2}这些从文件名字符串中分割出来就好了。
> > 
> > 
> > <img alt="image" width="219" src="https://user-images.githubusercontent.com/57703720/220547022-235a971a-41aa-4d96-99b8-608537a8a221.png">
> > 这是我现在的文件格式，但是还是不行，不知道是什么问题
> 
> 请问一下，可以分享一下你的数据集嘛？

是数据的问题，我下的数据有的文件命名有误，我写了个脚本读出了存在问题的文件位置，改了好了之后再按照自己的文件格式修改了一下读取键值对的那行代码就好了，数据集的话网上可以免费下载的。

**Comment by saisusmitha** [comment]
@jaceqin @zhao9chen99999 Can you tell me did you guys download data from the original site? because the folders have namings like BraTS20_Training_001/BraTS20_Training_001_flair.nii.gz and are 240x240x155. is this the same for you? Also i used the BRATSDataset3D to load data - what does o = torch.tensor(nib_img.get_fdata())[:,:,slice] this line means - selecting only one slice is used for training? I have saved these input images as png but they looked incorrect can you kindly tell me how to load these properly? below are the incorrect 
![BraTS20_Training_333input_image_00](https://user-images.githubusercontent.com/24909249/230215712-ea354f51-07f5-4e69-a4c3-21501ca48c2b.png)
![BraTS20_Training_333input_image_01](https://user-images.githubusercontent.com/24909249/230215718-e090b5e4-dca6-4c14-8a8e-cd075c75c62f.png)
![BraTS20_Training_333input_image_02](https://user-images.githubusercontent.com/24909249/230215722-d8b2ca94-8dac-40e6-86d2-85aabaff776b.png)
![BraTS20_Training_333input_image_03](https://user-images.githubusercontent.com/24909249/230215726-0772b664-ab74-466e-9d16-5d46c5f15e6a.png)
![BraTS20_Training_333input_image_04](https://user-images.githubusercontent.com/24909249/230215728-ced34229-28f2-4091-85e7-35c44091436a.png)
png of the nii.gz
