### ISSUE TITLE
Problems of sample

### ISSUE THREAD

**Issue by riokoh** [WuJunde/MedSegDiff#4]
1) log.txt and progress.csv will not output anything. 
2) when segmentation_sample.py is running, the terminal says there are connection-errors. 
3) i set num_ensemble=5 but just get one output image. from the terminal, it seems that something stop the iteration. 

what parameters or arguments should i revise or what can i do?

![J`Y4%GR1O_}XW{`2_%}F7SR](https://user-images.githubusercontent.com/113956389/206350443-8d50c77d-5236-4bc1-a814-e9d3ce9d7104.png)
![E5%P7GDZ1 _U9BP98GBNYN](https://user-images.githubusercontent.com/113956389/206350514-bc99e303-b29c-495d-9f62-67b076b27b7a.png)
![8`LP) @{L0 RJDNGP1 EHE8](https://user-images.githubusercontent.com/113956389/206350520-8345aa80-6bf8-4edc-926f-26822d33a874.png)
![I6F2R41@NC8B$R33E9G`X5L](https://user-images.githubusercontent.com/113956389/206350521-8f7ca9ad-606c-4a54-9fe1-dee4628e25b3.png)

**Comment by WuJunde** [comment]
1. it is ok log.txt and progress.csv don't output meaningful things in sampling, they are used to record the training loss. log.txt will only record the things you show in figure 2.
2. it doesn't matter. the warning is caused by visdom, which is used to visualize the intermediate results. it will not effect the results even if it can't work. the connection problem may be because your server cannot link the internet normally.
3. it's right. it outputs a single fused image.

**Comment by riokoh** [comment]
Thanks a lot! 👍
